apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.accountDeletionJobName }}
spec:
  schedule: {{ .Values.accountDeletionJobSchedule }}
  timeZone: "Asia/Kolkata"
  # It specifies how to treat concurrent executions of a job that is created by this CronJob
  # Forbid : The CronJob does not allow concurrent runs; if it is time for a new job run and the previous job run hasn't finished yet, the CronJob skips the new job run
  concurrencyPolicy: Forbid 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: Never